# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
'''
sum()是加總；a.sum()與np.sum(a)是陣列內加總，不過前者是array，後者是np
'''

'\nsum()是加總；a.sum()與np.sum(a)是陣列內加總，不過前者是array，後者是np\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件



In [7]:
import numpy as np

A = np.random.random((5, 5))
A= (A-A.min())/(A.max()-A.min())

print(A)

[[0.21582713 0.08647058 0.51288379 0.67615527 0.1788453 ]
 [0.99776034 0.8195676  0.61333265 0.59066178 0.01569884]
 [1.         0.90261038 0.90275163 0.25186301 0.09349568]
 [0.65447453 0.75625026 0.28067631 0.62018937 0.        ]
 [0.70437167 0.83834815 0.46360853 0.44706913 0.60290751]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [8]:
B=np.random.random(10)
B[B.argmax()]=-1
print(B)

[ 0.84914208  0.59238623  0.75649058 -1.          0.34456983  0.32977456
  0.0406176   0.7888216   0.58428168  0.73672808]
